### ISSUE TITLE
Better version/hash replacement strategy

### ISSUE THREAD

**Issue by piousdeer** [snowfallorg/drift#2]
I've noticed that --auto-hash causes silent failure if the current hash is an empty string.

flake.nix
```nix
{
  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixos-23.11";

    snowfall-lib = {
      url = "github:snowfallorg/lib";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    snowfall-drift = {
      url = "github:snowfallorg/drift";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = inputs:
    inputs.snowfall-lib.mkFlake {
      inherit inputs;
      src = ./.;

      channels-config = { allowUnfree = true; };

      snowfall = {
        root = ./.;
        namespace = "drift-test";
      };
    };
}
```
packages/firefox-gnome-theme/default.nix
```nix
{ pkgs, ... }:
let
  name = "firefox-gnome-theme";
  version = "1";
  hash = "";
  owner = "rafaelmardojai";
  repo = "firefox-gnome-theme";
in pkgs.stdenv.mkDerivation {
  inherit name version;

  src = pkgs.fetchFromGitHub {
    owner = owner;
    repo = repo;
    rev = "v${version}";
    sha256 = hash;
  };

  installPhase = ''
    cp -r . $out
  '';

  passthru.update = pkgs.writeShellScriptBin "update-my-package" ''
    set -euo pipefail

    latest="$(${pkgs.curl}/bin/curl -s "https://api.github.com/repos/${owner}/${repo}/releases?per_page=1" | ${pkgs.jq}/bin/jq -r ".[0].tag_name" | ${pkgs.gnused}/bin/sed 's/^v//')"

    drift rewrite --auto-hash --new-version "$latest"
  '';
}
```
```
drift rewrite --name firefox-gnome-theme --file packages/firefox-gnome-theme/default.nix --current-version 1 --new-version 122 --auto-hash
```
Observing default.nix in a text editor, first the version is updated, then the whole file becomes a bunch of hashes (a result of `s.replaceAll("", hash)`), then it is quickly reverted to its original state (#1).

Updating the version (from 1 to 122) also replaced the `1` in `per_page=1`.

**Comment by jakehamilton** [comment]
I've added a check to fail if the current hash doesn't exist, but `auto-hash` is specified. It may be possible to do some more advanced parsing of the Nix file to search for the version, it's also possible that the version is collected from elsewhere and we wouldn't be able to find it even if we traversed the AST. I think the solution here is to use a version like `"v1"` or even specify `version = "1"` so that the number can be replaced safely. Otherwise it's possible that the same text will be found in multiple places in the file (some of which are invalid).
